site_name: pyvdk
site_description: VK toolkit
site_author: lightmanLP & mikk357
repo_name: UT1C/pyvdk
repo_url: https://github.com/UT1C/pyvdk

theme:
    name: readthedocs
    favicon: assets\icon.png

extra_css:
    - assets\css\code.css

plugins:
    - search
    - macros:
        include_dir: .

markdown_extensions:
    - footnotes
    - attr_list
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - toc:
        permalink: "#"
        toc_depth: "1-6"

nav:
    - Основное:
        - Введение: intro.md
        - Создание хендлеров: handlers.md
        - Правила: rules.md
        - Вызов методов API: api_methods_call.md
        - Инструменты: tools.md
        - API Reference: api_reference.md
    - Дополнительно:
        - Changelog: additional/changelog.md
