site_name: pyvdk
site_description: VK toolkit
site_author: lightmanLP & mikk357
repo_name: UT1C/pyvdk
repo_url: https://github.com/UT1C/pyvdk

theme: readthedocs

plugins:
    - search
    - macros:
        include_dir: .

markdown_extensions:
    - footnotes
    - attr_list
    - admonition
    - toc:
        permalink: "#"
        toc_depth: "1-6"

nav:
    - Основное:
        - Введение: intro.md
        - Инструменты: tools.md
        - Вызов методов API: api_methods_call.md
        - API Reference: api_reference.md
    - Дополнительно:
        - Changelog: additional\changelog.md
