site_name: pyvdk
site_description: VK toolkit
site_author: lightmanLP & mikk357
repo_name: UT1C/pyvdk
repo_url: https://github.com/UT1C/pyvdk

theme: readthedocs

plugins:
    - search

nav:
    - Home: index.md
    - Введение: intro.md
    - API Reference: api_reference.md