site_name: pyvdk
site_description: VK toolkit
site_author: lightmanLP & mikk357
repo_name: UT1C/pyvdk
repo_url: https://github.com/UT1C/pyvdk

theme:
    name: readthedocs
    highlightjs: false
    hljs_languages:
        - python

extra_css:
    - assets/css/autodoc.css
    - assets/css/codehilite/extra.css
    - assets/css/codehilite/themes/friendly.css

plugins:
    - search
    - macros:
        include_dir: .

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: false
    - footnotes
    - attr_list
    - admonition
    - codehilite:
        guess_lang: false
    - mkautodoc
    - toc:
        permalink: "#"
        toc_depth: "1-6"

nav:
    - Основное:
        - Введение: intro.md
        - Создание хендлеров: handlers.md
        - Правила: rules.md
        - Вызов методов API: api_methods_call.md
        - Инструменты: tools.md
        - API Reference: api_reference.md
    - Дополнительно:
        - Changelog: additional/changelog.md
