from .base_response import BaseResponse
from .account import (
    ChangePasswordResponse,
    GetActiveOffersResponse,
    GetAppPermissionsResponse,
    GetBannedResponse,
    GetCountersResponse,
    GetInfoResponse,
    GetProfileInfoResponse,
    GetPushSettingsResponse,
    SaveProfileInfoResponse
)
from .ads import (
    AddOfficeUsersResponse,
    CheckLinkResponse,
    CreateAdsResponse,
    CreateCampaignsResponse,
    CreateClientsResponse,
    CreateTargetGroupResponse,
    DeleteAdsResponse,
    DeleteCampaignsResponse,
    DeleteClientsResponse,
    GetAccountsResponse,
    GetAdsLayoutResponse,
    GetAdsTargetingResponse,
    GetAdsResponse,
    GetBudgetResponse,
    GetCampaignsResponse,
    GetCategoriesResponse,
    GetClientsResponse,
    GetDemographicsResponse,
    GetFloodStatsResponse,
    GetLookalikeRequestsResponse,
    GetMusiciansResponse,
    GetOfficeUsersResponse,
    GetPostsReachResponse,
    GetRejectionReasonResponse,
    GetStatisticsResponse,
    GetSuggestionsCitiesResponse,
    GetSuggestionsRegionsResponse,
    GetSuggestionsResponse,
    GetSuggestionsSchoolsResponse,
    GetTargetGroupsResponse,
    GetTargetingStatsResponse,
    GetUploadURLResponse,
    GetVideoUploadURLResponse,
    ImportTargetContactsResponse,
    RemoveOfficeUsersResponse,
    UpdateAdsResponse,
    UpdateCampaignsResponse,
    UpdateClientsResponse
)
from .apps import (
    GetCatalogResponse,
    GetFriendsListResponse,
    GetLeaderboardExtendedResponse,
    GetLeaderboardResponse,
    GetScopesResponse,
    GetScoreResponse,
    GetResponse,
    SendRequestResponse
)
from .auth import (
    RestoreResponse
)
from .base import (
    BoolResponse,
    GetUploadServerResponse,
    OkResponse
)
from .board import (
    AddTopicResponse,
    CreateCommentResponse,
    GetCommentsExtendedResponse,
    GetCommentsResponse,
    GetTopicsExtendedResponse,
    GetTopicsResponse
)
from .database import (
    GetChairsResponse,
    GetCitiesByIdResponse,
    GetCitiesResponse,
    GetCountriesByIdResponse,
    GetCountriesResponse,
    GetFacultiesResponse,
    GetMetroStationsByIdResponse,
    GetMetroStationsResponse,
    GetRegionsResponse,
    GetSchoolClassesResponse,
    GetSchoolsResponse,
    GetUniversitiesResponse
)
from .docs import (
    AddResponse,
    GetByIdResponse,
    GetTypesResponse,
    GetUploadServer,
    GetResponse,
    SaveResponse,
    SearchResponse
)
from .downloaded_games import (
    PaidStatusResponse
)
from .fave import (
    AddTagResponse,
    GetPagesResponse,
    GetTagsResponse,
    GetExtendedResponse,
    GetResponse
)
from .friends import (
    AddListResponse,
    AddResponse,
    AreFriendsExtendedResponse,
    AreFriendsResponse,
    DeleteResponse,
    GetAppUsersResponse,
    GetByPhonesResponse,
    GetListsResponse,
    GetMutualResponse,
    GetMutualTargetUidsResponse,
    GetOnlineOnlineMobileResponse,
    GetOnlineResponse,
    GetRecentResponse,
    GetRequestsExtendedResponse,
    GetRequestsNeedMutualResponse,
    GetRequestsResponse,
    GetSuggestionsResponse,
    GetFieldsResponse,
    GetResponse,
    SearchResponse
)
from .gifts import (
    GetResponse
)
from .groups import (
    AddAddressResponse,
    AddCallbackServerResponse,
    AddLinkResponse,
    CreateResponse,
    EditAddressResponse,
    GetAddressesResponse,
    GetBannedResponse,
    GetByIdResponse,
    GetCallbackConfirmationCodeResponse,
    GetCallbackServersResponse,
    GetCallbackSettingsResponse,
    GetCatalogInfoExtendedResponse,
    GetCatalogInfoResponse,
    GetCatalogResponse,
    GetInvitedUsersResponse,
    GetInvitesExtendedResponse,
    GetInvitesResponse,
    GetLongPollServerResponse,
    GetLongPollSettingsResponse,
    GetMembersFieldsResponse,
    GetMembersFilterResponse,
    GetMembersResponse,
    GetRequestsFieldsResponse,
    GetRequestsResponse,
    GetSettingsResponse,
    GetTokenPermissionsResponse,
    GetExtendedResponse,
    GetResponse,
    IsMemberExtendedResponse,
    IsMemberResponse,
    IsMemberUserIdsExtendedResponse,
    IsMemberUserIdsResponse,
    SearchResponse
)
from .leads import (
    CheckUserResponse,
    CompleteResponse,
    GetStatsResponse,
    GetUsersResponse,
    MetricHitResponse,
    StartResponse
)
from .likes import (
    AddResponse,
    DeleteResponse,
    GetListExtendedResponse,
    GetListResponse,
    IsLikedResponse
)
from .market import (
    AddAlbumResponse,
    AddResponse,
    CreateCommentResponse,
    DeleteCommentResponse,
    GetAlbumByIdResponse,
    GetAlbumsResponse,
    GetByIdExtendedResponse,
    GetByIdResponse,
    GetCategoriesResponse,
    GetCommentsResponse,
    GetExtendedResponse,
    GetResponse,
    RestoreCommentResponse,
    SearchExtendedResponse,
    SearchResponse
)
from .messages import (
    CreateChatResponse,
    DeleteChatPhotoResponse,
    DeleteConversationResponse,
    DeleteResponse,
    EditResponse,
    GetByConversationMessageIdResponse,
    GetByIdExtendedResponse,
    GetByIdResponse,
    GetChatPreviewResponse,
    GetChatChatIdsFieldsResponse,
    GetChatChatIdsResponse,
    GetChatFieldsResponse,
    GetChatResponse,
    GetConversationMembersResponse,
    GetConversationsByIdExtendedResponse,
    GetConversationsByIdResponse,
    GetConversationsResponse,
    GetHistoryAttachmentsResponse,
    GetHistoryResponse,
    GetInviteLinkResponse,
    GetLastActivityResponse,
    GetLongPollHistoryResponse,
    GetLongPollServerResponse,
    IsMessagesFromGroupAllowedResponse,
    JoinChatByInviteLinkResponse,
    MarkAsImportantResponse,
    PinResponse,
    SearchConversationsResponse,
    SearchResponse,
    SendResponse,
    SendUserIdsResponse,
    SetChatPhotoResponse
)
from .newsfeed import (
    GetBannedExtendedResponse,
    GetBannedResponse,
    GetCommentsResponse,
    GetListsExtendedResponse,
    GetListsResponse,
    GetMentionsResponse,
    GetRecommendedResponse,
    GetSuggestedSourcesResponse,
    GetResponse,
    SaveListResponse,
    SearchExtendedResponse,
    SearchResponse
)
from .notes import (
    AddResponse,
    CreateCommentResponse,
    GetByIdResponse,
    GetCommentsResponse,
    GetResponse
)
from .notifications import (
    GetResponse,
    MarkAsViewedResponse,
    SendMessageResponse
)
from .orders import (
    CancelSubscriptionResponse,
    ChangeStateResponse,
    GetAmountResponse,
    GetByIdResponse,
    GetUserSubscriptionByIdResponse,
    GetUserSubscriptionsResponse,
    GetResponse,
    UpdateSubscriptionResponse
)
from .pages import (
    GetHistoryResponse,
    GetTitlesResponse,
    GetVersionResponse,
    GetResponse,
    ParseWikiResponse,
    SaveAccessResponse,
    SaveResponse
)
from .photos import (
    CopyResponse,
    CreateAlbumResponse,
    CreateCommentResponse,
    DeleteCommentResponse,
    GetAlbumsCountResponse,
    GetAlbumsResponse,
    GetAllCommentsResponse,
    GetAllExtendedResponse,
    GetAllResponse,
    GetByIdExtendedResponse,
    GetByIdResponse,
    GetCommentsExtendedResponse,
    GetCommentsResponse,
    GetMarketUploadServerResponse,
    GetMessagesUploadServerResponse,
    GetNewTagsResponse,
    GetTagsResponse,
    GetUploadServerResponse,
    GetUserPhotosExtendedResponse,
    GetUserPhotosResponse,
    GetWallUploadServerResponse,
    GetExtendedResponse,
    GetResponse,
    PutTagResponse,
    RestoreCommentResponse,
    SaveMarketAlbumPhotoResponse,
    SaveMarketPhotoResponse,
    SaveMessagesPhotoResponse,
    SaveOwnerCoverPhotoResponse,
    SaveOwnerPhotoResponse,
    SaveWallPhotoResponse,
    SaveResponse,
    SearchResponse
)
from .polls import (
    AddVoteResponse,
    CreateResponse,
    DeleteVoteResponse,
    GetByIdResponse,
    GetVotersResponse
)
from .pretty_cards import (
    CreateResponse,
    DeleteResponse,
    EditResponse,
    GetByIdResponse,
    GetUploadURLResponse,
    GetResponse
)
from .search import (
    GetHintsResponse
)
from .secure import (
    CheckTokenResponse,
    GetAppBalanceResponse,
    GetSMSHistoryResponse,
    GetTransactionsHistoryResponse,
    GetUserLevelResponse,
    GiveEventStickerResponse,
    SendNotificationResponse
)
from .stats import (
    GetPostReachResponse,
    GetResponse
)
from .status import (
    GetResponse
)
from .storage import (
    GetKeysResponse,
    GetResponse,
    GetV5110Response,
    GetWithKeysResponse
)
from .stories import (
    GetBannedExtendedResponse,
    GetBannedResponse,
    GetByIdExtendedResponse,
    GetByIdResponse,
    GetPhotoUploadServerResponse,
    GetStatsResponse,
    GetVideoUploadServerResponse,
    GetViewersExtendedV5115Response,
    GetViewersExtendedResponse,
    GetV5113Response,
    GetResponse,
    UploadResponse
)
from .streaming import (
    GetServerUrlResponse
)
from .users import (
    GetFollowersFieldsResponse,
    GetFollowersResponse,
    GetSubscriptionsExtendedResponse,
    GetSubscriptionsResponse,
    GetResponse,
    SearchResponse
)
from .utils import (
    CheckLinkResponse,
    GetLastShortenedLinksResponse,
    GetLinkStatsExtendedResponse,
    GetLinkStatsResponse,
    GetServerTimeResponse,
    GetShortLinkResponse,
    ResolveScreenNameResponse
)
from .video import (
    AddAlbumResponse,
    CreateCommentResponse,
    GetAlbumByIdResponse,
    GetAlbumsByVideoExtendedResponse,
    GetAlbumsByVideoResponse,
    GetAlbumsExtendedResponse,
    GetAlbumsResponse,
    GetCommentsExtendedResponse,
    GetCommentsResponse,
    GetExtendedResponse,
    GetResponse,
    RestoreCommentResponse,
    SaveResponse,
    SearchExtendedResponse,
    SearchResponse
)
from .wall import (
    CreateCommentResponse,
    EditResponse,
    GetByIdExtendedResponse,
    GetByIdResponse,
    GetCommentExtendedResponse,
    GetCommentResponse,
    GetCommentsExtendedResponse,
    GetCommentsResponse,
    GetRepostsResponse,
    GetExtendedResponse,
    GetResponse,
    PostAdsStealthResponse,
    PostResponse,
    RepostResponse,
    SearchExtendedResponse,
    SearchResponse
)
from .widgets import (
    GetCommentsResponse,
    GetPagesResponse
)
